export const Books = [
    {
        title: 'JavaScript and jQuery (3rd Edition)',
        author: 'Zak Ruvalcaba',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51lNgvdIdPL._SX398_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 51.97,
        shipping: 'FREE',
        ISBN: '978-1943872053',
        description: 'Today, you ll find JavaScript and jQuery used everywhere on the web, from small individual sites to the largest commercial sites like Google, Amazon, and Facebook. That s why every web developer needs to have at least a basic set of JavaScript and jQuery skills.',
        editReview: 'This is a must-have book for anyone wanting to master web development front-end UI work (HTML3/CSS3/JavaScript/JQuery). Currently I am in the corporate consulting world, but I have taught in universities, corporate training and vocational schools. Hats off to Murach and the JQuery authors.',
        pages: 620,
        publisher: 'Mike Murach & Associates',
        published: "February 20 2014",

    },
    {
        title: 'Mastering React Native ',
        author: 'Eric Masiello',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51OqHiEyDtL._SX404_BO1,204,203,200_.jpg',
        rating: 4,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 44.99,
        shipping: 'FREE',
        ISBN: '978-1785885785',
        description: 'React Native has completely revolutionized mobile development by empowering JavaScript developers',
        editReview: 'ric Masiello is a lead software engineer for Vistaprint Digital. Formerly, Eric worked as a principal frontend engineer for the Advisory Board Company and built mobile apps for the Education Advisory Board. Eric has worked primarily as a frontend/UI developer for over 10 years and freelances as a website designer/developer. He has taught frontend topics at General Assembly in Washington, D.C. and was a technical reviewer for Mastering ReactJS, a video by Packt Publishing.',
        pages: 496,
        publisher: 'Packt Publishing - ebooks Account',
        published: "January 11 2017",

    },
    {
        title: 'A Smarter Way to Learn JavaScript',
        author: 'Mark Myers',
        image: 'https://images-na.ssl-images-amazon.com/images/I/512KPmZIG7L._SX348_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 10.78,
        shipping: 'FREE',
        ISBN: '978-1497408180',
        description: 'Learning JavaScript is hell because of two problems. I remove the problems, and you start having fun. The first problem is retention. You remember only ten or twenty percent of what you read. That spells failure. To become fluent in a computer language, you have to retain pretty much everything.  ',
        editReview: 'A few years ago I set out to teach myself JavaScript by reading programming books. It was such a struggle that I decided I must have lost some learning ability over the years. Then it hit me... I was not a bad learner. The books were bad teachers! I fought my way through a dozen books, and by brute effort, learned JavaScript. But I had to design exercises for myself. Without practice, I could not retain anything. JavaScript, I learned, is not that hard. The books make it hard. So I wrote a book that makes ',
        pages: 254,
        publisher: 'CreateSpace Independent Publishing Platform',
        published: "March 20 2014",

    },
    {
        title: 'JavaScript and JQuery: Interactive Front-End Web Development',
        author: 'Jon Duckett',
        image: 'https://images-na.ssl-images-amazon.com/images/I/41Z6LTD8QmL._SX400_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 23.07,
        shipping: 'FREE',
        ISBN: '978-1943872053',
        description: 'Basic programming concepts - assuming no prior knowledge of programming beyond an ability to create a web page using HTML & CSS',
        editReview: 'nside it s beautifully designed, clearly laid out, and adds plenty of visual examples alongside the instructive text (Web User, August 2014 Forget dry references and cheesy examples. This beautifully designed visual guide takes you from the basics to sophisticated JavaScript techniques for making websites interactive and engaging in a way that is, in itself, interactive and engaging (ZDNet, September 2014',
        pages: 640,
        publisher: 'Wiley; 1 edition',
        published: "June 30 2014",

    },
    {
        title: 'JavaScript: The Good Parts',
        author: 'ouglas Crockford',
        image: 'https://images-na.ssl-images-amazon.com/images/I/5131OWtQRaL._SX381_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 19.11,
        shipping: 'FREE',
        ISBN: '978-0596517748',
        description: 'Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript that is more reliable, readable, and maintainable than the language as a whole—a subset you can use to create truly extensible and efficient code.',
        editReview: 'Unearthing the Excellence in JavaScript',
        pages: 176,
        publisher: 'O\'Reilly Media; 1st edition ',
        published: "May 1 2008",

    },
    {
        title: 'JavaScript: The Definitive Guide: Activate Your Web Pages',
        author: 'David Flanagan',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51WD-F3GobL._SX379_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 21.92,
        shipping: 'FREE',
        ISBN: '978-0596805524',
        description: 'Since 1996, JavaScript: The Definitive Guide has been the bible for JavaScript programmers—a programmer\'s guide and comprehensive reference to the core language and to the client-side JavaScript APIs defined by web browsers.',
        editReview: 'The 6th edition of JavaScript: The Definitive Guide includes 125 examples that you can view and download from from examples.oreilly.com/9780596805531/ or from github.com/davidflanagan/javascript6_examples ',
        pages: 1096,
        publisher: 'O\'Reilly Media',
        published: "May 13 2011",

    },
    {
        title: 'Eloquent JavaScript',
        author: 'Marijn Haverbeke',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51IKycqTPUL._SX376_BO1,204,203,200_.jpg',
        rating: 4,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 31.96,
        shipping: 'FREE',
        ISBN: '978-1593275846',
        description: 'JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.',
        editReview: 'Marijn Haverbeke is an independent developer and author, focused primarily on programming languages and tools for programmers. He spends most of his time working on open source software, such as the CodeMirror editor and the Tern type inference engine.',
        pages: 472,
        publisher: 'No Starch Press',
        published: "December 7 2014",

    },
    {
        title: 'Python Machine Learning: Machine Learning and Deep Learning with Python, scikit-learn, and TensorFlow',
        author: 'Sebastian Raschka',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51Q6SfhrrTL._SX404_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 39.99,
        shipping: 'FREE',
        ISBN: '978-1787125933',
        description: 'A practical approach to key frameworks in data science, machine learning, and deep learning',
        editReview: '"I bought the first version of this book, and now also the second. The new version is very comprehensive. If you are using Python - it\'s almost a reference. I also like the emphasis on neural networks (and TensorFlow - which (in my view is where the Python community is heading. I am also planning to use this book in my teaching at Oxford University. The data pre-processing sections are also good. I found the sequence flow slightly unusual - but for an expert level audience, it\'s not a major issue."',
        pages: 622,
        publisher: 'Packt Publishing',
        published: "September 20, 2017",

    },
    {
        title: 'Python Crash Course: A Hands-On, Project-Based Introduction to Programming',
        author: 'Eric Matthes',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51PZ6YIfe9L._SX376_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 27.16,
        shipping: 'FREE',
        ISBN: '978-1593276034',
        description: 'Python Crash Course is a fast-paced, thorough introduction to Python that will have you writing programs, solving problems, and making things that work in no time.',
        editReview: 'This is a must-have book for anyone wanting to master web development front-end UI work (HTML3/CSS3/JavaScript/JQuery. Currently I am in the corporate consulting world, but I have taught in universities, corporate training and vocational schools. Hats off to Murach and the JQuery authors.',
        pages: 560,
        publisher: 'No Starch Press',
        published: "November 1 2015",

    },
    {
        title: 'Python: For Beginners: A Crash Course Guide To Learn Python in 1 Week',
        author: 'Timothy C. Needham',
        image: 'https://images-na.ssl-images-amazon.com/images/I/41jfWR-2LEL._SX331_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 17.95,
        shipping: 'FREE',
        ISBN: '978-1549776670',
        description: 'Python is a simple yet powerful programming language that can enable you to start thinking like a programmer right from the beginning. It is very readable and the stress many beginners face about memorizing arcane syntax typically presented by other programming languages will not affect you at all. Conversely, you will be able to concentrate on learning concepts and paradigms of programming. ',
        editReview: ' This book shall introduce you to an easy way to learn Python in just 7 days and in this time, be able to complete your own projects! By reading the book and implementing what you learn herein, you will realize just why major institutions like NASA, Google, Mozilla, Yahoo, Dropbox, IBM, Facebook and many others prefer to use python in their core products, services and business processes. ',
        pages: 135,
        publisher: 'Independently',
        published: "September 21 2017",

    },
    {
        title: 'A Smarter Way to Learn Python: Learn it faster. Remember it longer',
        author: 'Mark Myers',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51D4DhxTZ9L._SX348_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 19.95,
        shipping: 'FREE',
        ISBN: 978-1943872053,
        description: 'I was smart enough to earn an honors degree in philosophy from Harvard, but an aptitude test told me to avoid computer programming. I\'m sure it was right. But then I designed a learning system for myself that quadrupled my aptitude for learning computer languages. It worked so well for me that I\'ve used it to teach coding to grandmothers, cab drivers, musicians, and 50,000 other newbies.',
        editReview: 'A few years ago I set out to teach myself Web development by reading programming books. It was such a struggle that I decided I must have lost some learning ability over the years. Then it hit me... I wasn\'t a bad learner. The books were bad teachers! I fought my way through a dozen books, and by brute effort, learned to build websites. But I had to design exercises for myself. Without practice, I couldn\'t retain anything.',
        pages: 236,
        publisher: 'CreateSpace Independent Publishing Platform',
        published: "August 9 2017",

    },
    {
        title: 'Learning Python, 5th Edition',
        author: 'Mark Lutz',
        image: 'https://images-na.ssl-images-amazon.com/images/I/515iBchIIzL._SX379_BO1,204,203,200_.jpg',
        rating: 4,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 64.97,
        shipping: 'FREE',
        ISBN: 978-1943872053,
        description: 'Get a comprehensive, in-depth introduction to the core Python language with this hands-on book. Based on author Mark Lutz’s popular training course, this updated fifth edition will help you quickly write efficient, high-quality code with Python. It’s an ideal way to begin, whether you’re new to programming or a professional developer versed in other languages.',
        editReview: 'Mark is the author of the three O’Reilly books: Learning Python, Programming Python, and Python Pocket Reference, all currently in fourth or fifth editions. He has been using and promoting Python since 1992, started writing Python books in 1995, and began teaching Python classes in 1997. As of Spring 2013, Mark has instructed 260 Python training sessions, taught roughly 4,000 students in live classes, and written Python books that have sold 400,000 units and been translated to at least a dozen languages.',
        pages: 1648,
        publisher: 'O\'Reilly Media',
        published: "July 6 2015",

    },
    {
        title: 'Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython',
        author: 'Wes McKinney ',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51-s8fr3F2L._SX379_BO1,204,203,200_.jpg',
        rating: 4,
        editionType: 'Paperback',
        stockPosition: 'Out of Stock',
        price: 32.87,
        shipping: 'FREE',
        ISBN: '978-1491957660',
        description: 'Get complete instructions for manipulating, processing, cleaning, and crunching datasets in Python. Updated for Python 3.6, the second edition of this hands-on guide is packed with practical case studies that show you how to solve a broad set of data analysis problems effectively. You’ll learn the latest versions of pandas, NumPy, IPython, and Jupyter in the process.',
        editReview: 'Wes McKinney is a New York?based software developer and entrepreneur. After finishing his undergraduate degree in mathematics at MIT in 2007, he went on to do quantitative finance work at AQR Capital Management in Greenwich, CT. Frustrated by cumbersome data analysis tools, he learned Python and started building what would later become the pandas project. He\'s now an active member of the Python data community and is an advocate for the use of Python in data analysis, finance, and statistical computing applications.',
        pages: 544,
        publisher: 'O\'Reilly Media',
        published: "October 20 2017",

    },
    {
        title: 'The Well-Grounded Rubyist',
        author: 'David A. Black',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51qtp4NzjRL._SX397_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'Out of Stock',
        price: 26.98,
        shipping: 'FREE',
        ISBN: '978-1617291692',
        description: 'The Well-Grounded Rubyist, Second Edition addresses both newcomers to Ruby as well as Ruby programmers who want to deepen their understanding of the language. This beautifully written and totally revised second edition includes coverage of features that are new in Ruby 2.1, as well as expanded and updated coverage of aspects of the language that have changed.',
        editReview: 'David A. Black is an internationally-known software developer, author, trainer, speaker, and event organizer. He is a Ruby standard library contributor and one of the founders of Ruby Central, Inc., the parent organization of the official international Ruby and Ruby on Rails conferences. David works at 2U, Inc. in New York City.',
        pages: 536,
        publisher: 'Manning Publications',
        published: "July 4 2014",

    },
    {
        title: 'Eloquent Ruby',
        author: 'Russ Olsen',
        image: 'https://images-na.ssl-images-amazon.com/images/I/41KtNo1H-DL._SX380_BO1,204,203,200_.jpg',
        rating: 4.5,
        editionType: 'Paperback',
        stockPosition: 'In Stock',
        price: 37.93,
        shipping: 'FREE',
        ISBN: '978-0321584106',
        description: 'It’s easy to write correct Ruby code, but to gain the fluency needed to write great Ruby code, you must go beyond syntax and absorb the “Ruby way” of thinking and problem solving. In Eloquent Ruby, Russ Olsen helps you write Ruby like true Rubyists do–so you can leverage its immense, surprising power.',
        editReview: 'Ruby\'s syntactic and logical aesthetics represent the pinnacle for elegance and beauty in the ALGOL family of programming languages. Eloquent Ruby is the perfect book to highlight this masterful language and Russ\'s blend of wit and wisdom is certain to entertain and inform.',
        pages: 448,
        publisher: 'Addison-Wesley',
        published: "February 11 2011",

    },

]